---

- name: APT | Install cachefilesd
  apt: name=cachefilesd state=present

- name: LINEINFILE | Enable cachefilesd
  lineinfile: dest=/etc/default/cachefilesd regexp='^#?RUN' line='RUN=yes'

- name: FILE | Create cache directory
  file: >
    path={{ nfs_cache_path }}
    state=directory
    owner=root
    group=root

- name: SERVICE | Ensure cachefilesd is started
  service: name=cachefilesd state=started
