---

- name: APT | Install minimal packages
  apt: pkg=nfs-common update_cache=yes cache_valid_time=3600 state=present

- name: INCLUDE | Install NFS server
  include: server/main.yml
  when: nfs_server

- name: INCLUDE | Install NFS client
  include: client/main.yml
  when: nfs_client
